plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 4.0
  Exclude:
    - 'benchmark/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20
