plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: disable
  TargetRubyVersion: 4.0
  Exclude:
    - 'benchmark/**/*'
    - 'coverage/**/*'
    - 'doc/**/*'
    - 'pkg/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20
