module CDC
  module Core
    class ProcessorResult
      def self.success: (untyped event) -> ProcessorResult
      def self.failure: (untyped error) -> ProcessorResult
    end

    class ChangeEvent
    end

    class TransactionEnvelope
    end
  end
end